services:
  - type: web
    name: project-management-backend
    env: java
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/project-management-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
    autoDeploy: true

databases:
  - name: project_management_db
    plan: free
    databaseName: project_management_db
    user: postgres
